env:
  global:
    - secure: "W3PaYhPnJFCaG6TW5Xc0wtggdEqcreTQcHThmIo5Eqs/jUL2toiUiv3ZWlhzR3tkphLvt2KeaQe83BR6RTifYjSmnmAePj0Gw5res1AXzN95OsKEk3nMiTZbVP+PuTTbQZJga8B31nRUBiAMQ6FsNlpGq7E8sp9N65lnR3mGHAE="

language: python

branches:
  only:
    - master

before_install:
  - pip install six sphinx sphinx_bootstrap_theme jsonschema pyyaml
  - bash -x ./install-texlive.sh
  - export PATH=$PWD/texlive/bin/x86_64-linux:$PATH

install:
  - make html latexpdf

script:
  - bash -x ./travis_deploy.sh
